# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x08protobuf\"\xc7\x01\n\x0fMessageEnvelope\x12\x10\n\x08TargetId\x18\x01 \x01(\r\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x0f\n\x07Payload\x18\x03 \x01(\x0c\x12#\n\x04Type\x18\x04 \x01(\x0e\x32\x15.protobuf.MessageType\x12!\n\x07Players\x18\x05 \x03(\x0b\x32\x10.protobuf.Player\x12\x1e\n\x04user\x18\x06 \x01(\x0b\x32\x10.protobuf.Player\x12\x0c\n\x04list\x18\x07 \x03(\t\x12\x0f\n\x07intList\x18\x08 \x03(\r\"#\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\r*$\n\x0bMessageType\x12\n\n\x06SYSTEM\x10\x00\x12\t\n\x05\x41LARM\x10\x01\x62\x06proto3')

_MESSAGETYPE = DESCRIPTOR.enum_types_by_name['MessageType']
MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
SYSTEM = 0
ALARM = 1


_MESSAGEENVELOPE = DESCRIPTOR.message_types_by_name['MessageEnvelope']
_PLAYER = DESCRIPTOR.message_types_by_name['Player']
MessageEnvelope = _reflection.GeneratedProtocolMessageType('MessageEnvelope', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEENVELOPE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MessageEnvelope)
  })
_sym_db.RegisterMessage(MessageEnvelope)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
  'DESCRIPTOR' : _PLAYER,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Player)
  })
_sym_db.RegisterMessage(Player)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=266
  _MESSAGETYPE._serialized_end=302
  _MESSAGEENVELOPE._serialized_start=28
  _MESSAGEENVELOPE._serialized_end=227
  _PLAYER._serialized_start=229
  _PLAYER._serialized_end=264
# @@protoc_insertion_point(module_scope)
